mysite/AppOne/urls.py
from django.urls import path
from AppOne import views

app_name = 'AppOne'

urlpatterns = [
    path('AppOne/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from AppOne import views


urlpatterns = [
    path('', views.index, name='index'),
    path('AppOne/', include('AppOne.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
] 

mysite/AppOne/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    # Create relationship (don't inherit from User)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    # Additionaal fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    
    def __str__(self):
        return self.user.username
    

mysite/AppOne/forms.py
from django import forms
from django.contrib.auth.models import User
from AppOne.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username','email','password')
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

mysite/AppOne/views.py
from django.shortcuts import render
from AppOne.forms import UserForm, UserProfileInfoForm


# for Login Form
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required




# Create your views here.
def index(request):
    insert_text = "I'm learning about Django."
    return render(request, 'AppOne/index.html', {'insert_text': insert_text})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

def register(request):
    registered = False
    
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
        
            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
                
                
            profile.save()
            registered = True
            
        else:
            print(user_form.errors, profile_form.errors)
            
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        
    return render(request, 'AppOne/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user =  authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")        
        else:
            print("Someone tried to login and failed!")
            print(f"Username: {username} and password: {password}")
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'AppOne/login.html')

mysite/templates/AppOne/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Home</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url "index" %}">Django Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav  me-auto mb-2 mb-lg-0 ps-lg-5">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "index" %}">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url "admin:index" %}">Admin</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url "AppOne:register" %}">Registration</a>
                    </li>


                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="{% url "special" %}">Welcome, {{user.username|title }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url "AppOne:user_login" %}">Login</a>
                    </li>
                    {% endif %}
                    
                
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock  %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

mysite/templates/AppOne/index.html
{% extends "AppOne\base.html" %}
{% load static %}
{% block body_block %}
    <h1> HELLO WORLD!</h1>
    <h4> {{ insert_text }} </h4>
    {% if user.is_authenticated %}
        <p>Welcome, {{ user.username|title }}, this is your table. </p>
        <table class="table table-dark table-striped">
            <thead>
                <tr class="">
                    <th scope="col">#</th>
                    <th scope="col">Column1</th>
                    <th scope="col">Column2</th>
                    <th scope="col">Column3</th>
                </tr>
            </thead>
            <tr>
                <th scope="row">1</th>
                <td> Data1 </td>
                <td> Data2 </td>
                <td> Data3 </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td> Data4 </td>
                <td> Data5 </td>
                <td> Data6 </td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td> Data4 </td>
                <td> Data5 </td>
                <td> Data6 </td>
            </tr>
            <tr>
                <th scope="row">4</th>
                <td> Data4 </td>
                <td> Data5 </td>
                <td> Data6 </td>
            </tr>
        </table>

    {% endif %}
    
{% endblock  %}



mysite/templates/AppOne/login.html
{% extends "AppOne\base.html" %}
{% load static %}
{% block body_block %}
    <h3> Please Login</h3>
    <hr class="divider"> 
    <form method="post" action="{% url "AppOne:user_login" %}">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" id="username" placeholder="Enter your username"/>
        </br>
        </br>
        <label for="password">Password: </label>
        <input type="password" name="password" id="password" placeholder="Enter your password"/>
        </br>
        </br>
        <input type="submit" name="login" id="login" value="Login"/>
    </form>

{% endblock  %}

mysite/templates/AppOne/registration.html
{% extends "AppOne/base.html" %}
{% load static %}
{% block body_block %}
    <div>
        {% if registered %}
            <h1> Thank you for Registring !</h1>
        {% else %}
        <h1> Please Register!</h1>
        <hr class="divider">
        <form enctype="multipart/form-data" method="post" >
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input class="btn btn-primary mb-auto" type="submit" name="submit" value="Register" />
        </form>
        
        {% endif %}
    </div>
{% endblock  %}